/*
 * Copyright 2026 badjeff
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_ANALOG_AXIS_HIRES_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_ANALOG_AXIS_HIRES_H_

/**
 * @brief Sensor API Attributes.
 */
#define ANALOG_AXIS_HIRES_ATTR_RESUME 0

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INPUT_ANALOG_AXIS_HIRES_H_ */
